### ISSUE TITLE
Expose Prefect Core Version on Server/UI

### ISSUE THREAD

**Issue by AlessandroLollo** [PrefectHQ/server#120]
## Current behavior

Actually, there's no easy way to get the version of Prefect Core running in my environment.

## Proposed behavior

Expose Prefect Core version so that it can be shown in Prefect UI/Server.

## Example

Having Prefect Core version under the Prefect Core logo would be nice!
![Screenshot 2020-10-28 at 14 31 40](https://user-images.githubusercontent.com/1206243/97442826-8f64c980-192a-11eb-8dce-2d4af1858010.png)

**Comment by madkinsz** [comment]
@znicholasbrown should this be in the ui repo?

**Comment by znicholasbrown** [comment]
Hm no @madkinsz, I think the version will need to be added from Core and passed as an environment variable to the UI or Server containers, the latter is preferable since the UI can run independently of Server. If we go that way, we'd want to expose the version through the `api` route... we already do this but it's represented as a commit hash instead of a semver.

**Comment by madkinsz** [comment]
> Hm no @madkinsz, I think the version will need to be added from Core and passed as an environment variable to the UI or Server containers, the latter is preferable since the UI can run independently of Server. If we go that way, we'd want to expose the version through the `api` route... we already do this but it's represented as a commit hash instead of a semver.

Great, thanks for the background. I'll look into this a bit more.

**Comment by madkinsz** [comment]
@AlessandroLollo heads up that this done!

**Comment by AlessandroLollo** [comment]
Great!

**Comment by AlessandroLollo** [comment]
> @AlessandroLollo heads up that this done!

Great!
