### ISSUE TITLE
Resolve security vulnerabilities in Docker containers of Prefect server

### ISSUE THREAD

**Issue by niakki** [PrefectHQ/server#197]
Hello,
We are evaluating prefect core to replace our workflow management. As part of security protocol all container images are scanned which included all the 5 docker containers of prefect core (server, Apollo, ui, Hasura/graphql & Postgres:11). All of these containers seem to have vulnerabilities and most of them are medium to low.
However, the ones which are critical & high needs to be resolved before we can use them for prod, based on our observation these packages are system libs (like linux kernel, shadow, glibc etc. something which prefect doesn’t directly use). Is it possible to update the base image to say Ubuntu 20.4 (in our tests between Debian and ubuntu, the latter seems to have just about 16 [1 medium rest all low vulnerabilities])? 

Screen shots -

![Screen Shot 2021-02-26 at 17 01 29](https://user-images.githubusercontent.com/36913184/109295575-f9e43280-7854-11eb-9396-be67e548c8b7.png)
![Screen Shot 2021-02-26 at 17 01 44](https://user-images.githubusercontent.com/36913184/109295580-fc468c80-7854-11eb-98a8-0a88dfff7057.png)
![Screen Shot 2021-02-26 at 16 15 05](https://user-images.githubusercontent.com/36913184/109295583-fd77b980-7854-11eb-84ee-5010c999add8.png)

_PS - Scans have been made using GCP’s vulnerability scan service in GCR_

Any other recommended approach we could follow to over come this issue is greatly appreciated. :slightly_smiling_face:

[Slack reference](https://prefect-community.slack.com/archives/CL09KU1K7/p1614269132285700?thread_ts=1614260765.274600&cid=CL09KU1K7)

_Originally posted by @niakki in https://github.com/PrefectHQ/prefect/discussions/4180_

**Comment by madkinsz** [comment]
Thanks for submitting the issue @niakki 

For mostly internal purposes, we have a few courses of action here.

## Apollo

Based on the official `node-slim` image. Recently upgraded in https://github.com/PrefectHQ/server/pull/153. We could

- Upgrade major versions and see if it breaks anything (14.x.x-> 15.x.x)
- Upgrade minor version and see if it fixes security concerns (14.15.x -> 14.16.x)
- Explore alternative node linux distros available at https://hub.docker.com/_/node/
- Install node manually in a base image of our choice ie Ubuntu

## Server

Based on the official `python-3.7-slim` image.

Consider
- Using `slim-buster` to designate a newer debian version, not sure what version of debian is running now
- Using `alpine` instead of debain
- Install python manually in a base image of our choice ie Ubuntu

**Comment by madkinsz** [comment]
Following https://github.com/PrefectHQ/server/pull/198 the Apollo/Server images are on the latest stable version of Debian. We've audited the critical/high CVEs for this version and they do not apply to our use. This version of Debian is widely used and I don't think we'll deviate from it at this time to satisfy external security policies.

@niakki -- You can create custom images that are based on Ubuntu instead if you need to do so to satisfy your requirements. It seems likely that you could just change the base image then install python / node as needed.

**Comment by niakki** [comment]
> Following #198 the Apollo/Server images are on the latest stable version of Debian. We've audited the critical/high CVEs for this version and they do not apply to our use. This version of Debian is widely used and I don't think we'll deviate from it at this time to satisfy external security policies.
> 
> @niakki -- You can create custom images that are based on Ubuntu instead if you need to do so to satisfy your requirements. It seems likely that you could just change the base image then install python / node as needed.

thank you @madkinsz I'll try that.

**Comment by madkinsz** [comment]
Hi @noemtz -- can you clarify how that CVE is relevant? 

> However, binaries running with an effective UID of 0 are unaffected.

There's only a root user in these containers so this CVE does not affect you.

```
❯ docker run -it prefecthq/server bash      
root@80cd93bc5486:/prefect-server# echo $UID
0
root@80cd93bc5486:/prefect-server# echo $EUID
0
```

**Comment by noemtz** [comment]
Hi @madkinsz,

It is relevant for us because Azure highlights this vulnerability on it and we are very strict with respect to security, as per Azure Security Policy ("Running containers as root user should be avoided") we need to deploy the container without with a different user than root (for this we need to create an image with this container as base) and also because as per Microsoft Defender for Cloud scanner this image has a high risk vulnerability. Thoughts?

**Comment by madkinsz** [comment]
We will likely update the Debian base image soon, if you open a PR I will review it. Generally I'd recommend building an image that fits your needs directly if you have strict security requirements. This is an open source project and it's difficult for us to assess and address security cases that are beyond our intended uses. Automated scans do not always capture realistic scenarios.

**Comment by noemtz** [comment]
I totally understand, I can help with the PR. Thanks for the prompt response.
