### ISSUE TITLE
Launch server + UI without Docker

### ISSUE THREAD

**Issue by gatesn** [PrefectHQ/server#79]
Would it be possible to document how to start the server + UI without a Docker dependency?

`Please note the server requires Docker and Docker Compose to be running.`

Page reference: https://docs.prefect.io/core/getting_started/installation.html

**Comment by jcrist** [comment]
Moved this issue to the server repository, as it has more to do with prefect server than prefect core.

**Comment by GZangl** [comment]
@jcrist - thanks a lot.
In the meantime, I have figured out how to get rid of the permission error:
I am running the server with following command from the bin folder: "sudo python3 prefect server start"

**Comment by znicholasbrown** [comment]
Hi all - yesterday was a holiday for the Prefect team (Labor Day in the US) so we're tackling your issue today. 

We're working on some documentation for spinning up the various services in Server independent of the `prefect server start` command, which I believe will address @gatesn's issue; we'll update this ticket when that documentation is ready.


@GZangl and @JonathanLoscalzo - I'd encourage you to join our [Community Slack](https://join.slack.com/t/prefect-community/shared_invite/zt-at5l6diu-m7EsnFdpjgGL68l0WMox~w) channel for some help triaging your specific issues (@GZangl I think you've already done this) as it looks like they're probably not related to the original post.

**Comment by GZangl** [comment]
@znicholasbrown ,yes Nicholas, I moved to Slack and sorry for hijacking this issue. But it is related, as my problems started with the same error message as @JonathanLoscalzo had and I also share the confusion about the usage of docker and docker-composer.
The installation turns out to be very smooth, if all requirements are met and you work your way around the Linux permissions. So, my conclusion is: people have to be very carefully reading the error messages during installation and try to install the erroneous wheels manually (in my case psutil). This is a bit of a stretch for people like me, who lack proper understanding ;)

**Comment by JonathanLoscalzo** [comment]
> Hi all - yesterday was a holiday for the Prefect team (Labor Day in the US) so we're tackling your issue today.
> 
> We're working on some documentation for spinning up the various services in Server independent of the `prefect server start` command, which I believe will address @gatesn's issue; we'll update this ticket when that documentation is ready.
> 
> @GZangl and @JonathanLoscalzo - I'd encourage you to join our [Community Slack](https://join.slack.com/t/prefect-community/shared_invite/zt-at5l6diu-m7EsnFdpjgGL68l0WMox~w) channel for some help triaging your specific issues (@GZangl I think you've already done this) as it looks like they're probably not related to the original post.

You are right, I apologise for misunderstanding. I will go to slack. 

And @GZangl also thanks!

**Comment by ReinierKop** [comment]
> We're working on some documentation for spinning up the various services in Server independent of the prefect server start command, which I believe will address @gatesn's issue; we'll update this ticket when that documentation is ready.

Hi @znicholasbrown , any update on this particular bit of documentation/news? Our clients require us to deploy our software on premises, mostly on windows server VMs, which unfortunately often times are unable to enable hyper-v/WSL (and therefore docker).

**Comment by znicholasbrown** [comment]
Hi @ReinierKop - this was something we ended up abandoning due to maintenance costs; one of the reasons we chose to use containers for the various services is exactly what you've described with Windows Server VMs - we don't have the ability to maintain all of the services in the Prefect stack in all of the environments such a feature would suggest. Using containerization allows us to maintain a single environment and its dependencies and focus instead on building features. 

Apologies for not closing this issue earlier!

**Comment by ReinierKop** [comment]
Alright, too bad :) Thanks for answering!

**Comment by madkinsz** [comment]
That said, the services are all run in-process for development in https://github.com/PrefectHQ/server/blob/master/src/prefect_server/cli/dev.py and if you can run the infrastructure `apollo` / `hasura` / `postgres` yourself outside of containers you should be able to accomplish this.

**Comment by ReinierKop** [comment]
Yup, will try this definitely! We're already very happy Prefect Core works on windows without containers so this would simply be the cherry :). Thanks again!
